spring:
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/microservice_db?authSource=admin

  application:
    name: RATING-SERVICE


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8083